/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 src/assets/t_shirt.glb 
Author: Tabbuso (https://sketchfab.com/Tabbuso)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tshirt-5a21282b2e454d1696547148f617d3d0
Title: Tshirt
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/t_shirt.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.039}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.FABRIC_1_FRONT_4193} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.FABRIC_1_FRONT_4193} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.FABRIC_1_FRONT_4193} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.FABRIC_1_FRONT_4193} />
      </group>
    </group>
  )
}

useGLTF.preload('/t_shirt.glb')
